[package]
name = "sparse_colamd"
edition = "2024"
version.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
sparse_array = { version = "*", path = "../sparse_array" }
