[workspace]
resolver = "3"
members = [
    "crates/sparse_colamd",
    "crates/sparse_colamd/valid",
]

[package]
name = "sparse"
version = "0.5.1"
edition = "2024"
description = "Sparse"
repository = "https://github.com/lokyhark/sparse"
license = "MIT"
keywords = ["sparse"]
categories = ["mathematics"]
readme = "README.md"

[workspace.package]
version = "0.5.1"
description = "Sparse"
repository = "https://github.com/lokyhark/sparse"
license = "MIT"
keywords = ["sparse"]
categories = ["mathematics"]
readme = "README.md"


[dependencies]
sparse_array = { version = "0.5.1", path = "crates/sparse_array" }
sparse_colamd = { version = "0.5.1", path = "crates/sparse_colamd" }

[lints.clippy]
all = "warn"
cargo = "warn"
complexity = "warn"
correctness = "warn"
pedantic = "warn"
perf = "warn"
style = "warn"
suspicious = "warn"
