[workspace]
resolver = "3"
members = ["valid/colamd"]

[package]
name = "sparse"
version = "0.5.1"
edition = "2024"
description = "Sparse"
repository = "https://github.com/lokyhark/sparse"
license = "MIT"
keywords = ["sparse"]
categories = ["mathematics"]
readme = "README.md"

[workspace.package]
version = "0.5.0"
description = "Sparse"
repository = "https://github.com/lokyhark/sparse"
license = "MIT"
keywords = ["sparse"]
categories = ["mathematics"]
readme = "README.md"


[dependencies]

[lints.clippy]
all = "warn"
cargo = "warn"
complexity = "warn"
correctness = "warn"
pedantic = "warn"
perf = "warn"
style = "warn"
suspicious = "warn"
